// resources/js/Pages/Contacto.vue
<template>
    <div class="bg-white">
      <Head><title>Contacto | Santa Emma</title></Head>
      <Header />
      <Hero title="Contáctanos" subtitle="Estamos listos para asesorarte y acompañarte en tus proyectos." image="/img/h1.jpg" />

      <FormularioContacto />

      <ContactFooter />
    </div>
  </template>

  <script setup>
  import { Head } from '@inertiajs/vue3'
  import Header from '@/Components/Header.vue'
  import Hero from '@/Components/Hero.vue'

  import FormularioContacto from '@/Components/FormularioContacto.vue'
  import ContactFooter from '@/Components/ContactFooter.vue'
  </script>

// resources/js/Pages/Contacto.jsx
import { Head } from '@inertiajs/react';
import Header from '@/Components/Header.jsx';
import Hero from '@/Components/Hero.jsx';
import FormularioContacto from '@/Components/FormularioContacto.jsx';
import ContactFooter from '@/Components/ContactFooter.jsx';

export default function Contacto() {
    return (
        <div className="bg-white">
            <Head title="Contacto | Santa Emma" />
            <Header />
            <Hero title="Contáctanos" subtitle="Estamos listos para asesorarte y acompañarte en tus proyectos." image="/img/h1.jpg" />
            <FormularioContacto />
            <ContactFooter />
        </div>
    );
}
