// resources/js/Pages/Nosotros.jsx
import { Head } from '@inertiajs/react';
import Header from '@/Components/Header.jsx';
import Hero from '@/Components/Hero.jsx';
import Footer from '@/Components/Whitefooter.jsx';
import ResumenEmpresa from '@/Components/ResumenEmpresa.jsx';
import Historia from '@/Components/Historia.jsx';
import Equipo from '@/Components/Equipo.jsx';
import Especialidades from '@/Components/Especialidades.jsx';

export default function Nosotros() {
    return (
        <div className="bg-white">
            <Head title="Nosotros | Santa Emma" />
            <Header />
            <Hero title="Construcción con sentido estratégico" subtitle="Obras que generan valor. Inversiones que transforman territorio." image="/img/h1.jpg" />
            <ResumenEmpresa />
            <Historia />
            <Especialidades />
            <Equipo />
            <Footer light />
        </div>
    );
}

// resources/js/Pages/Nosotros.vue
<template>
    <div class="bg-white">
      <Head><title>Nosotros | Santa Emma</title></Head>
      <Header />

      <Hero
        title="Construcción con sentido estratégico"
        subtitle="Obras que generan valor. Inversiones que transforman territorio."
        image="/img/h1.jpg"
      />

      <ResumenEmpresa />
      <Historia />
      <Equipo />
      <Especialidades />
      <Certificaciones />

      <Footer />
    </div>
  </template>

  <script setup>
  import { Head } from '@inertiajs/vue3'
  import Header from '@/Components/Header.vue'
  import Hero from '@/Components/Hero.vue'
  import Footer from '@/Components/Footer.vue'

  import ResumenEmpresa from '@/Components/ResumenEmpresa.vue'
  import Historia from '@/Components/Historia.vue'
  import Equipo from '@/Components/Equipo.vue'
  import Especialidades from '@/Components/Especialidades.vue'
  import Certificaciones from '@/Components/Certificaciones.vue'
  </script>
