// resources/js/Pages/Profile/Show.jsx
import AppLayout from '@/Layouts/AppLayout.jsx';
import SectionBorder from '@/Components/SectionBorder.jsx';
import UpdateProfileInformationForm from './Partials/UpdateProfileInformationForm.jsx';
import UpdatePasswordForm from './Partials/UpdatePasswordForm.jsx';
import TwoFactorAuthenticationForm from './Partials/TwoFactorAuthenticationForm.jsx';
import LogoutOtherBrowserSessionsForm from './Partials/LogoutOtherBrowserSessionsForm.jsx';
import DeleteUserForm from './Partials/DeleteUserForm.jsx';
import { usePage } from '@inertiajs/react';

export default function Show({ sessions }) {
    const { props } = usePage();
    return (
        <AppLayout title="Perfil" header={<h2 className="text-xl font-semibold leading-tight text-stone-800">Perfil</h2>}>
            <div className="py-10">
                <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
                    <UpdateProfileInformationForm user={props.auth?.user} />
                    <SectionBorder />
                    <UpdatePasswordForm />
                    {props.jetstream?.canManageTwoFactorAuthentication && (
                        <>
                            <SectionBorder />
                            <TwoFactorAuthenticationForm requiresConfirmation={props.confirmsTwoFactorAuthentication} />
                        </>
                    )}
                    <SectionBorder />
                    <LogoutOtherBrowserSessionsForm sessions={sessions} />
                    {props.jetstream?.hasAccountDeletionFeatures && (
                        <>
                            <SectionBorder />
                            <DeleteUserForm />
                        </>
                    )}
                </div>
            </div>
        </AppLayout>
    );
}

// resources/js/Pages/Profile/Show.vue
<script setup>
import AppLayout from '@/Layouts/AppLayout.vue';
import DeleteUserForm from '@/Pages/Profile/Partials/DeleteUserForm.vue';
import LogoutOtherBrowserSessionsForm from '@/Pages/Profile/Partials/LogoutOtherBrowserSessionsForm.vue';
import SectionBorder from '@/Components/SectionBorder.vue';
import TwoFactorAuthenticationForm from '@/Pages/Profile/Partials/TwoFactorAuthenticationForm.vue';
import UpdatePasswordForm from '@/Pages/Profile/Partials/UpdatePasswordForm.vue';
import UpdateProfileInformationForm from '@/Pages/Profile/Partials/UpdateProfileInformationForm.vue';

defineProps({
    confirmsTwoFactorAuthentication: Boolean,
    sessions: Array,
});
</script>

<template>
    <AppLayout title="Profile">


        <div>
            <div class="max-w-7xl mx-auto py-10 sm:px-6 lg:px-8">
                <div v-if="$page.props.jetstream.canUpdateProfileInformation">
                    <UpdateProfileInformationForm :user="$page.props.auth.user" />

                    <SectionBorder />
                </div>

                <div v-if="$page.props.jetstream.canUpdatePassword">
                    <UpdatePasswordForm class="mt-10 sm:mt-0" />

                    <SectionBorder />
                </div>

                <div v-if="$page.props.jetstream.canManageTwoFactorAuthentication">
                    <TwoFactorAuthenticationForm
                        :requires-confirmation="confirmsTwoFactorAuthentication"
                        class="mt-10 sm:mt-0"
                    />

                    <SectionBorder />
                </div>

                <LogoutOtherBrowserSessionsForm :sessions="sessions" class="mt-10 sm:mt-0" />

                <template v-if="$page.props.jetstream.hasAccountDeletionFeatures">
                    <SectionBorder />

                    <DeleteUserForm class="mt-10 sm:mt-0" />
                </template>
            </div>
        </div>
    </AppLayout>
</template>
