// resources/js/Layouts/AppLayout.jsx
import { Head } from '@inertiajs/react';
import { useState } from 'react';
import {
    ApplicationMark,
    Banner,
    Dropdown,
    DropdownLink,
    Link,
    NavLink,
    ResponsiveNavLink,
    currentRoute,
    routeTo,
    router,
    usePage,
} from '@/Components/Common.jsx';

export default function AppLayout({ title, header, children }) {
    const [showingNavigationDropdown, setShowingNavigationDropdown] = useState(false);
    const { props } = usePage();
    const user = props?.auth?.user || {};
    const jetstream = props?.jetstream || {};

    const logout = () => router.post(routeTo('logout'));

    return (
        <div>
            <Head title={title} />
            <Banner />
            <div className="min-h-screen bg-stone-100">
                <nav className="border-b border-yellow-200 bg-gradient-to-br from-white to-yellow-50 shadow-sm">
                    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                        <div className="flex h-16 justify-between">
                            <div className="flex items-center">
                                <Link href={routeTo('dashboard')} className="flex shrink-0 items-center">
                                    <ApplicationMark className="block h-9 w-auto" />
                                </Link>
                                <div className="hidden space-x-8 sm:ms-10 sm:flex">
                                    <NavLink href={routeTo('home', undefined, '/')} active={currentRoute('home')}>Inicio</NavLink>
                                    <NavLink href={routeTo('dashboard')} active={currentRoute('dashboard')}>Panel de Usuario</NavLink>
                                </div>
                            </div>

                            <div className="hidden sm:ms-6 sm:flex sm:items-center">
                                <Dropdown
                                    trigger={
                                        <button type="button" className="inline-flex items-center rounded-md border bg-white px-3 py-2 text-sm font-medium text-stone-500 transition hover:text-stone-700">
                                            {user.name || 'Usuario'}
                                            <span className="ms-2">⌄</span>
                                        </button>
                                    }
                                >
                                    <div className="block px-4 py-2 text-xs text-stone-400">Gestionar cuenta</div>
                                    <DropdownLink href={routeTo('profile.show')}>Perfil</DropdownLink>
                                    {jetstream.hasApiFeatures && <DropdownLink href={routeTo('api-tokens.index')}>Tokens de API</DropdownLink>}
                                    <div className="my-2 border-t border-stone-200" />
                                    <DropdownLink as="button" onClick={logout}>Cerrar sesión</DropdownLink>
                                </Dropdown>
                            </div>

                            <div className="-me-2 flex items-center sm:hidden">
                                <button onClick={() => setShowingNavigationDropdown(!showingNavigationDropdown)} className="rounded-md p-2 text-stone-400 transition hover:bg-stone-100 hover:text-stone-500">
                                    {showingNavigationDropdown ? '×' : '☰'}
                                </button>
                            </div>
                        </div>
                    </div>

                    <div className={(showingNavigationDropdown ? 'block' : 'hidden') + ' sm:hidden'}>
                        <div className="space-y-1 pb-3 pt-2">
                            <ResponsiveNavLink href={routeTo('dashboard')} active={currentRoute('dashboard')}>Dashboard</ResponsiveNavLink>
                        </div>
                        <div className="border-t border-stone-200 pb-1 pt-4">
                            <div className="px-4">
                                <div className="text-base font-medium text-stone-800">{user.name}</div>
                                <div className="text-sm font-medium text-stone-500">{user.email}</div>
                            </div>
                            <div className="mt-3 space-y-1">
                                <ResponsiveNavLink href={routeTo('profile.show')}>Perfil</ResponsiveNavLink>
                                {jetstream.hasApiFeatures && <ResponsiveNavLink href={routeTo('api-tokens.index')}>Tokens de API</ResponsiveNavLink>}
                                <ResponsiveNavLink as="button" onClick={logout}>Cerrar sesión</ResponsiveNavLink>
                            </div>
                        </div>
                    </div>
                </nav>

                {header && (
                    <header className="border-b border-stone-200 bg-gradient-to-br from-yellow-100 to-white shadow-sm">
                        <div className="mx-auto max-w-7xl px-4 py-10 text-center sm:px-6 lg:px-8">{header}</div>
                    </header>
                )}

                <main>{children}</main>
            </div>
        </div>
    );
}

// resources/js/Layouts/AppLayout.vue
<script setup>
import { ref } from 'vue';
import { Head, Link, router } from '@inertiajs/vue3';
import ApplicationMark from '@/Components/ApplicationMark.vue';
import Banner from '@/Components/Banner.vue';
import Dropdown from '@/Components/Dropdown.vue';
import DropdownLink from '@/Components/DropdownLink.vue';
import NavLink from '@/Components/NavLink.vue';
import ResponsiveNavLink from '@/Components/ResponsiveNavLink.vue';

defineProps({ title: String });

const showingNavigationDropdown = ref(false);

const switchToTeam = (team) => {
    router.put(route('current-team.update'), {
        team_id: team.id,
    }, {
        preserveState: false,
    });
};

const logout = () => {
    router.post(route('logout'));
};
</script>

<template>
  <div>
    <Head :title="title" />
    <Banner />

    <div class="min-h-screen bg-gray-100">
      <!-- NAVIGATION BAR -->
      <nav class="bg-gradient-to-br from-white to-yellow-50 border-b border-yellow-200 shadow-sm">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between h-16">
            <div class="flex items-center">
              <Link :href="route('dashboard')" class="shrink-0 flex items-center">
                <ApplicationMark class="block h-9 w-auto" />
              </Link>

              <div class="hidden sm:flex sm:ms-10 space-x-8">
  <NavLink :href="route('home')" :active="route().current('home')">
    Inicio
  </NavLink>
  <NavLink :href="route('dashboard')" :active="route().current('dashboard')">
    Panel de Usuario
  </NavLink>
</div>

            </div>

            <div class="hidden sm:flex sm:items-center sm:ms-6">
              <!-- Teams Dropdown -->
              <Dropdown v-if="$page.props.jetstream.hasTeamFeatures" align="right" width="60">
                <template #trigger>
                  <span class="inline-flex rounded-md">
                    <button type="button" class="inline-flex items-center px-3 py-2 border text-sm font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 transition">
                      {{ $page.props.auth.user.current_team.name }}
                      <svg class="ms-2 -me-0.5 size-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />
                      </svg>
                    </button>
                  </span>
                </template>
                <template #content>
                  <div class="w-60">
                    <div class="block px-4 py-2 text-xs text-gray-400">Manage Team</div>
                    <DropdownLink :href="route('teams.show', $page.props.auth.user.current_team)">Team Settings</DropdownLink>
                    <DropdownLink v-if="$page.props.jetstream.canCreateTeams" :href="route('teams.create')">Create New Team</DropdownLink>
                    <template v-if="$page.props.auth.user.all_teams.length > 1">
                      <div class="border-t border-gray-200 mt-2" />
                      <div class="block px-4 py-2 text-xs text-gray-400">Switch Teams</div>
                      <template v-for="team in $page.props.auth.user.all_teams" :key="team.id">
                        <form @submit.prevent="switchToTeam(team)">
                          <DropdownLink as="button">
                            <div class="flex items-center">
                              <svg v-if="team.id === $page.props.auth.user.current_team_id" class="me-2 size-5 text-green-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                              </svg>
                              <div>{{ team.name }}</div>
                            </div>
                          </DropdownLink>
                        </form>
                      </template>
                    </template>
                  </div>
                </template>
              </Dropdown>

              <!-- User Dropdown -->
              <Dropdown align="right" width="48">
                <template #trigger>
                  <span class="inline-flex rounded-md">
                    <button type="button" class="inline-flex items-center px-3 py-2 border text-sm font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 transition">
                      {{ $page.props.auth.user.name }}
                      <svg class="ms-2 -me-0.5 size-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                      </svg>
                    </button>
                  </span>
                </template>
                <template #content>
  <div class="block px-4 py-2 text-xs text-gray-400">Gestionar cuenta</div>
  <DropdownLink :href="route('profile.show')">Perfil</DropdownLink>
  <DropdownLink v-if="$page.props.jetstream.hasApiFeatures" :href="route('api-tokens.index')">Tokens de API</DropdownLink>
  <div class="border-t border-gray-200 my-2" />
  <form @submit.prevent="logout">
    <DropdownLink as="button">Cerrar sesión</DropdownLink>
  </form>
</template>

              </Dropdown>
            </div>

            <!-- Mobile Hamburger -->
            <div class="-me-2 flex items-center sm:hidden">
              <button @click="showingNavigationDropdown = !showingNavigationDropdown" class="p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 transition">
                <svg class="size-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path :class="{ 'hidden': showingNavigationDropdown, 'inline-flex': !showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  <path :class="{ 'hidden': !showingNavigationDropdown, 'inline-flex': showingNavigationDropdown }" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <!-- Responsive Menu -->
        <div :class="{ 'block': showingNavigationDropdown, 'hidden': !showingNavigationDropdown }" class="sm:hidden">
          <div class="pt-2 pb-3 space-y-1">
            <ResponsiveNavLink :href="route('dashboard')" :active="route().current('dashboard')">Dashboard</ResponsiveNavLink>
          </div>
          <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
              <div class="font-medium text-base text-gray-800">{{ $page.props.auth.user.name }}</div>
              <div class="font-medium text-sm text-gray-500">{{ $page.props.auth.user.email }}</div>
            </div>
            <div class="mt-3 space-y-1">
              <ResponsiveNavLink :href="route('profile.show')">Profile</ResponsiveNavLink>
              <ResponsiveNavLink v-if="$page.props.jetstream.hasApiFeatures" :href="route('api-tokens.index')">API Tokens</ResponsiveNavLink>
              <form method="POST" @submit.prevent="logout">
                <ResponsiveNavLink as="button">Log Out</ResponsiveNavLink>
              </form>
            </div>
          </div>
        </div>
      </nav>

      <!-- Mejorado: Slot Header con estilo elegante -->
      <header v-if="$slots.header" class="bg-gradient-to-br from-yellow-100 to-white shadow-sm border-b border-gray-200">
        <div class="max-w-7xl mx-auto px-4 py-10 sm:px-6 lg:px-8 text-center">
          <slot name="header" />
        </div>
      </header>

      <!-- Contenido principal -->
      <main>
        <slot />
      </main>
    </div>
  </div>
</template>
