// resources/js/Pages/Auth/ForgotPassword.vue
<script setup>
import { Head, useForm } from '@inertiajs/vue3';
import AuthenticationCard from '@/Components/AuthenticationCard.vue';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

defineProps({
    status: String,
});

const form = useForm({
    email: '',
});

const submit = () => {
    form.post(route('password.email'));
};
</script>

<template>
    <Head title="Restablecer contraseña" />

    <div class="relative min-h-screen flex items-center justify-center px-4 py-12 sm:px-6 lg:px-8 overflow-hidden bg-[#1c120a]">
        <!-- Fondo decorativo -->
        <div
            class="absolute inset-0 z-0 pointer-events-none animate-move-pattern"
            style="
                background-image: radial-gradient(circle at 25% 25%, #eab308 1px, transparent 1px);
                background-size: 60px 60px;
                opacity: 0.2;
            "
        ></div>

        <!-- Panel de recuperación -->
        <div class="relative z-10 w-full max-w-md space-y-6 bg-gradient-to-br from-[#eab308] to-white text-black shadow-xl rounded-xl p-8 sm:p-10 border border-yellow-300/20">
            <div class="flex justify-center">
                <AuthenticationCardLogo class="w-28 h-auto" />
            </div>

            <div class="text-sm text-gray-800 leading-relaxed">
                ¿Olvidaste tu contraseña? No hay problema. Solo ingresa tu correo electrónico y te enviaremos un enlace para que puedas restablecerla.
            </div>

            <div v-if="status" class="text-sm font-medium text-green-600 text-center">
                {{ status }}
            </div>

            <form @submit.prevent="submit" class="space-y-6">
                <div>
                    <InputLabel for="email" value="Correo electrónico" class="text-black" />
                    <TextInput
                        id="email"
                        v-model="form.email"
                        type="email"
                        class="mt-1 block w-full rounded-md bg-white text-black border-gray-300 placeholder-gray-400 focus:ring-[#eab308] focus:border-[#eab308]"
                        placeholder="tucorreo@ejemplo.com"
                        required
                        autofocus
                        autocomplete="username"
                    />
                    <InputError class="mt-2 text-red-600" :message="form.errors.email" />
                </div>

                <div class="flex items-center justify-end">
                    <PrimaryButton
                        class="bg-[#eab308] hover:bg-yellow-500 text-black font-semibold py-2 px-4 rounded-md transition"
                        :class="{ 'opacity-25': form.processing }"
                        :disabled="form.processing"
                    >
                        Enviar enlace de restablecimiento
                    </PrimaryButton>
                </div>
            </form>
        </div>
    </div>
</template>

// resources/js/Pages/Auth/ForgotPassword.jsx
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { useRef, useState } from 'react';
import AuthenticationCard from '@/Components/AuthenticationCard.jsx';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.jsx';
import Checkbox from '@/Components/Checkbox.jsx';
import InputError from '@/Components/InputError.jsx';
import InputLabel from '@/Components/InputLabel.jsx';
import PrimaryButton from '@/Components/PrimaryButton.jsx';
import TextInput from '@/Components/TextInput.jsx';
import { routeTo } from '@/Components/Common.jsx';

export default function ForgotPassword({ status }) {
    const form = useForm({ email: '' });
    const submit = (e) => { e.preventDefault(); form.post(routeTo('password.email')); };
    return (
        <AuthenticationCard logo={<AuthenticationCardLogo />}>
            <Head title="Restablecer contraseña" />
            <p className="mb-6 text-sm text-stone-600">Ingresa tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.</p>
            {status && <div className="mb-4 text-sm font-medium text-green-600">{status}</div>}
            <form onSubmit={submit}>
                <InputLabel htmlFor="email" value="Correo electrónico" />
                <TextInput id="email" value={form.data.email} onChange={(e) => form.setData('email', e.target.value)} type="email" className="mt-1 block w-full" required autoFocus autoComplete="username" />
                <InputError className="mt-2" message={form.errors.email} />
                <div className="mt-4 flex justify-end"><PrimaryButton disabled={form.processing}>Enviar enlace</PrimaryButton></div>
            </form>
        </AuthenticationCard>
    );
}
