// resources/js/Pages/Auth/Login.vue
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import AuthenticationCard from '@/Components/AuthenticationCard.vue';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.vue';
import Checkbox from '@/Components/Checkbox.vue';
import InputError from '@/Components/InputError.vue';
import InputLabel from '@/Components/InputLabel.vue';
import PrimaryButton from '@/Components/PrimaryButton.vue';
import TextInput from '@/Components/TextInput.vue';

defineProps({
    canResetPassword: Boolean,
    status: String,
});

const form = useForm({
    email: '',
    password: '',
    remember: false,
});

const submit = () => {
    form.transform(data => ({
        ...data,
        remember: form.remember ? 'on' : '',
    })).post(route('login'), {
        onFinish: () => form.reset('password'),
    });
};
</script>

<template>
    <Head title="Iniciar sesión" />

    <div class="relative min-h-screen flex items-center justify-center px-4 py-12 sm:px-6 lg:px-8 overflow-hidden bg-[#1c120a]">
        <!-- Fondo decorativo con patrón dorado -->
        <div
            class="absolute inset-0 z-0 pointer-events-none animate-move-pattern"
            style="
                background-image: radial-gradient(circle at 25% 25%, #eab308 1px, transparent 1px);
                background-size: 60px 60px;
                opacity: 0.2;
            "
        ></div>

        <!-- Panel del login -->
        <div class="relative z-10 w-full max-w-md space-y-8 bg-gradient-to-br from-[#eab308] to-white text-black shadow-xl rounded-xl p-8 sm:p-10 border border-yellow-300/20">
            <div class="flex justify-center">
                <AuthenticationCardLogo class="w-28 h-auto" />
            </div>

            <div v-if="status" class="text-center text-sm text-green-600 font-medium">
                {{ status }}
            </div>

            <form @submit.prevent="submit" class="space-y-6">
                <div>
                    <InputLabel for="email" value="Correo electrónico" class="text-black" />
                    <TextInput
                        id="email"
                        v-model="form.email"
                        type="email"
                        class="mt-1 block w-full rounded-md bg-white text-black border-gray-300 placeholder-gray-400 focus:ring-[#eab308] focus:border-[#eab308]"
                        placeholder="tucorreo@ejemplo.com"
                        required
                        autofocus
                        autocomplete="username"
                    />
                    <InputError class="mt-2 text-red-600" :message="form.errors.email" />
                </div>

                <div>
                    <InputLabel for="password" value="Contraseña" class="text-black" />
                    <TextInput
                        id="password"
                        v-model="form.password"
                        type="password"
                        class="mt-1 block w-full rounded-md bg-white text-black border-gray-300 placeholder-gray-400 focus:ring-[#eab308] focus:border-[#eab308]"
                        placeholder="••••••••"
                        required
                        autocomplete="current-password"
                    />
                    <InputError class="mt-2 text-red-600" :message="form.errors.password" />
                </div>

                <div class="flex items-center justify-between text-sm text-gray-800">
                    <label class="flex items-center">
                        <Checkbox v-model:checked="form.remember" name="remember" class="mr-2" />
                        Recordarme
                    </label>

                    <Link
                        v-if="canResetPassword"
                        :href="route('password.request')"
                        class="hover:text-[#eab308] text-black transition"
                    >
                        ¿Olvidaste tu contraseña?
                    </Link>
                </div>

                <div>
                    <PrimaryButton
                        class="w-full justify-center bg-[#eab308] hover:bg-yellow-500 text-black font-semibold py-2 px-4 rounded-md transition"
                        :class="{ 'opacity-25': form.processing }"
                        :disabled="form.processing"
                    >
                        Iniciar sesión
                    </PrimaryButton>
                </div>
            </form>
        </div>
    </div>
</template>

// resources/js/Pages/Auth/Login.jsx
import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { useRef, useState } from 'react';
import AuthenticationCard from '@/Components/AuthenticationCard.jsx';
import AuthenticationCardLogo from '@/Components/AuthenticationCardLogo.jsx';
import Checkbox from '@/Components/Checkbox.jsx';
import InputError from '@/Components/InputError.jsx';
import InputLabel from '@/Components/InputLabel.jsx';
import PrimaryButton from '@/Components/PrimaryButton.jsx';
import TextInput from '@/Components/TextInput.jsx';
import { routeTo } from '@/Components/Common.jsx';

export default function Login({ canResetPassword, status }) {
    const form = useForm({ email: '', password: '', remember: false });
    const submit = (e) => {
        e.preventDefault();
        form.transform((data) => ({ ...data, remember: data.remember ? 'on' : '' })).post(routeTo('login'), {
            onFinish: () => form.reset('password'),
        });
    };
    return (
        <div className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#1c120a] px-4 py-12">
            <Head title="Iniciar sesión" />
            <div className="relative z-10 w-full max-w-md space-y-8 rounded-xl border border-yellow-300/20 bg-gradient-to-br from-[#eab308] to-white p-8 text-black shadow-xl sm:p-10">
                <div className="flex justify-center"><AuthenticationCardLogo className="h-24 w-auto" /></div>
                {status && <div className="text-center text-sm font-medium text-green-700">{status}</div>}
                <form onSubmit={submit} className="space-y-6">
                    <div>
                        <InputLabel htmlFor="email" value="Correo electrónico" className="text-black" />
                        <TextInput id="email" value={form.data.email} onChange={(e) => form.setData('email', e.target.value)} type="email" className="mt-1 block w-full bg-white text-black" required autoFocus autoComplete="username" />
                        <InputError className="mt-2 text-red-700" message={form.errors.email} />
                    </div>
                    <div>
                        <InputLabel htmlFor="password" value="Contraseña" className="text-black" />
                        <TextInput id="password" value={form.data.password} onChange={(e) => form.setData('password', e.target.value)} type="password" className="mt-1 block w-full bg-white text-black" required autoComplete="current-password" />
                        <InputError className="mt-2 text-red-700" message={form.errors.password} />
                    </div>
                    <div className="flex items-center justify-between text-sm text-stone-800">
                        <label className="flex items-center gap-2"><Checkbox checked={form.data.remember} onChange={(v) => form.setData('remember', v)} name="remember" />Recordarme</label>
                        {canResetPassword && <Link href={routeTo('password.request')} className="text-black hover:text-yellow-700">¿Olvidaste tu contraseña?</Link>}
                    </div>
                    <PrimaryButton className="w-full justify-center" disabled={form.processing}>Iniciar sesión</PrimaryButton>
                </form>
            </div>
        </div>
    );
}
